Basic functionality

diff --git a/gh-cib b/gh-cib
--- a/gh-cib
+++ b/gh-cib
@@ -3,27 +3,18 @@ set -e
 
 read -p "Issue title: " title
 
-gh issue create --title "$title"
+output=$(gh issue create --title "$title" --body "" | tail -n 1)
 
-# Pass arguments through to another command
-# gh issue list "$@" -R cli/cli
+pattern='https://.*/issues/([0-9]+)'
+if [[ "$output" =~ $pattern ]]; then
+    issue_number=${BASH_REMATCH[1]} 
+    echo "Issue number is: $issue_number"
+else    
+    echo "Could not get issue number, output:"
+    echo $output
+    exit 1
+fi
 
-# Using the gh api command to retrieve and format information
-# QUERY='
-#   query($endCursor: String) {
-#     viewer {
-#       repositories(first: 100, after: $endCursor) {
-#         nodes {
-#           nameWithOwner
-#           stargazerCount
-#         }
-#       }
-#     }
-#   }
-# '
-# TEMPLATE='
-#   {{- range $repo := .data.viewer.repositories.nodes -}}
-#     {{- printf "name: %s - stargazers: %v\n" $repo.nameWithOwner $repo.stargazerCount -}}
-#   {{- end -}}
-# '
-# exec gh api graphql -f query="${QUERY}" --paginate --template="${TEMPLATE}"
+branch_title=$(echo $title | sed -E 's/([.~^:?*\[@{}<>|\\"''()`,]|[\]]|[[:space:]])+/_/g')
+
+git switch --create "issue-${issue_number}-${branch_title}"
